eureka:
  client:
    service-url:
      defaultZone: http://localhost:8076/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8086

spring:
  application:
    name: "api-gateway"
  main:
    web-application-type: reactive
  cloud:
    gateway:
     routes:
        - id: clinic-service
          uri: http://localhost:9090/
          predicates:
           - Path=/clinic-service/**

        - id: Authentication-Service
          uri: http://localhost:8082/
          predicates:
            - Path=//**

        - id:
          uri: http://localhost:8082/
          predicates:
            - Path=//**




