eureka:
  client:
    service-url:
      defaultZone: http://localhost:8076/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8086

spring:
  application:
    name: "api-gateway"
  main:
    web-application-type: reactive
  cloud:
    gateway:
     routes:
        - id: clinic-service
          uri: http://localhost:9090/
          predicates:
           - Path=/clinic-service/**

        - id: Authentication-Service
          uri: http://localhost:8082/
          predicates:
            - Path=/authentication_service/**

        - id: registration-service
          uri: http://localhost:8081/
          predicates:
            - Path=/register/**

        - id: Email-Service
          uri: http://localhost:9098/
          predicates:
            - Path=/email-service/**

        - id: appointment-service
          uri: http://localhost:8025/
          predicates:
            - Path=/appointmentservice/**

        - id: patient-service
          uri: http://localhost:9003/
          predicates:
            - Path=/patientService/**

        - id: payments-service
          uri: http://localhost:8088/
          predicates:
            - Path=/payment/**
