eureka:
  client:
    service-url:
      defaultZone: http://localhost:8076/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8086

spring:
  application:
    name: "api-gateway"
  main:
    web-application-type: reactive
  cloud:
    gateway:
     routes:
        - id: clinic-service
          uri: http://localhost:9090/
          predicates:
           - Path=/clinic-service/**

        - id: Authentication-Service
          uri: http://localhost:8082/
          predicates:
            - Path=/authentication-service/**

        - id: registration-service
          uri: http://localhost:8085/
          predicates:
            - Path=/registration-service/**

        - id: Email-Service
          uri: http://localhost:9098/
          predicates:
            - Path=/email-service/**

        - id: appointment-service
          uri: http://localhost:8025/
          predicates:
            - Path=/appointment-service/**

        - id: patient-service
          uri: http://localhost:9003/
          predicates:
            - Path=/patient-service/**

        - id: payment-service
          uri: http://localhost:8088/
          predicates:
            - Path=/payment-service/**

        - id: feedback-service
          uri: http://localhost:8089/
          predicates:
            - Path=/feedback-service/**

        - id: chat-service
          uri: http://localhost:9000/
          predicates:
            - Path=/chat-service/**
